# =============================================================================
# S3 — Simple Storage Service (file storage)
# =============================================================================
# S3 is AWS's object storage — like a hard drive in the cloud.
# Use cases in this app:
#   - ALB access logs (every HTTP request logged)
#   - CSV/PDF/Excel exports generated by the app
#   - Future: bank statement uploads before parsing
#
# S3 concepts:
#   Bucket:  a container (like a folder) — globally unique name
#   Object:  a file stored in a bucket
#   Key:     the file path/name inside the bucket
#   ACL:     access control (we keep everything private)
# =============================================================================

# ── Main app bucket ───────────────────────────────────────────────────────────
resource "aws_s3_bucket" "app" {
  # Bucket names must be globally unique across ALL AWS accounts.
  # Adding account ID makes it unique.
  bucket = "${var.app_name}-${data.aws_caller_identity.current.account_id}"

  tags = { Name = "${var.app_name}-storage" }
}

# Get current AWS account ID
data "aws_caller_identity" "current" {}

# Block ALL public access — this bucket is private
resource "aws_s3_bucket_public_access_block" "app" {
  bucket = aws_s3_bucket.app.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Enable versioning: keeps previous versions of files for 30 days
# Protects against accidental overwrites/deletes
resource "aws_s3_bucket_versioning" "app" {
  bucket = aws_s3_bucket.app.id
  versioning_configuration {
    status = "Enabled"
  }
}

# Encrypt all files at rest
resource "aws_s3_bucket_server_side_encryption_configuration" "app" {
  bucket = aws_s3_bucket.app.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# Lifecycle rules: automatically delete old files to control costs
resource "aws_s3_bucket_lifecycle_configuration" "app" {
  bucket = aws_s3_bucket.app.id

  # Delete ALB logs after 90 days
  rule {
    id     = "delete-old-alb-logs"
    status = "Enabled"
    filter { prefix = "alb-logs/" }
    expiration { days = 90 }
  }

  # Delete old exports after 30 days
  rule {
    id     = "delete-old-exports"
    status = "Enabled"
    filter { prefix = "exports/" }
    expiration { days = 30 }
  }

  # Delete non-current object versions after 30 days
  rule {
    id     = "expire-old-versions"
    status = "Enabled"
    filter {}
    noncurrent_version_expiration { noncurrent_days = 30 }
  }
}

# ALB needs permission to write access logs to this bucket
resource "aws_s3_bucket_policy" "alb_logs" {
  bucket = aws_s3_bucket.app.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect    = "Allow"
        Principal = { AWS = "arn:aws:iam::127311923021:root" }  # us-east-1 ELB account
        Action    = "s3:PutObject"
        Resource  = "${aws_s3_bucket.app.arn}/alb-logs/*"
      }
    ]
  })
}
