"""initial_schema_users_categories_expenses_income_budgets

Revision ID: d0624dedae75
Revises:
Create Date: 2026-05-27 09:44:02.722106+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d0624dedae75"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="User's email address (login identifier)",
        ),
        sa.Column(
            "username",
            sa.String(length=50),
            nullable=False,
            comment="Display username (shown in UI)",
        ),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=False,
            comment="bcrypt hashed password. NEVER store plaintext!",
        ),
        sa.Column(
            "role",
            sa.Enum("USER", "ADMIN", "SUPER_ADMIN", name="user_role"),
            nullable=False,
            comment="RBAC role: user | admin | super_admin",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="False = account suspended/deactivated",
        ),
        sa.Column(
            "is_verified",
            sa.Boolean(),
            nullable=False,
            comment="True = email address has been verified",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier (UUID v4)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was last updated",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Soft delete timestamp. NULL means active.",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "categories",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=True,
            comment="Owner user. NULL = system default category",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Category display name (e.g., Food, Transport, Salary)",
        ),
        sa.Column(
            "icon",
            sa.String(length=10),
            nullable=True,
            comment="Emoji or icon identifier for UI display",
        ),
        sa.Column(
            "color",
            sa.String(length=7),
            nullable=True,
            comment="Hex color code for UI display (#RRGGBB)",
        ),
        sa.Column(
            "category_type",
            sa.Enum("EXPENSE", "INCOME", "BOTH", name="category_type"),
            nullable=False,
            comment="Whether this category is for expenses, income, or both",
        ),
        sa.Column(
            "is_default",
            sa.Boolean(),
            nullable=False,
            comment="True = system default category, shown to all users",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier (UUID v4)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was last updated",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Soft delete timestamp. NULL means active.",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_categories_deleted_at"), "categories", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_categories_user_id"), "categories", ["user_id"], unique=False
    )
    op.create_index(
        "ix_categories_user_name", "categories", ["user_id", "name"], unique=False
    )
    op.create_table(
        "user_profiles",
        sa.Column(
            "user_id", sa.UUID(), nullable=False, comment="References the owner user"
        ),
        sa.Column(
            "first_name",
            sa.String(length=100),
            nullable=True,
            comment="User's first name",
        ),
        sa.Column(
            "last_name",
            sa.String(length=100),
            nullable=True,
            comment="User's last name",
        ),
        sa.Column(
            "avatar_url",
            sa.String(length=500),
            nullable=True,
            comment="URL to profile picture (S3 URL in production)",
        ),
        sa.Column("bio", sa.Text(), nullable=True, comment="Short bio or description"),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
            comment="Preferred currency (ISO 4217 code)",
        ),
        sa.Column(
            "timezone",
            sa.String(length=50),
            nullable=False,
            comment="User's timezone (IANA timezone name e.g. America/New_York)",
        ),
        sa.Column(
            "monthly_budget_limit",
            sa.Float(),
            nullable=True,
            comment="Monthly spending limit (None = no limit set)",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier (UUID v4)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was last updated",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Soft delete timestamp. NULL means active.",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_profiles_deleted_at"),
        "user_profiles",
        ["deleted_at"],
        unique=False,
    )
    op.create_table(
        "budgets",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "category_id",
            sa.UUID(),
            nullable=True,
            comment="Budget for this category. NULL = overall budget",
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Budget amount (how much is planned to spend)",
        ),
        sa.Column(
            "period_start",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Budget period start date (usually 1st of the month)",
        ),
        sa.Column(
            "period_end",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Budget period end date (usually last day of month)",
        ),
        sa.Column(
            "alert_threshold",
            sa.Float(),
            nullable=False,
            comment="Alert when this % of budget is used (0.80 = 80%)",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier (UUID v4)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was last updated",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Soft delete timestamp. NULL means active.",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_budgets_deleted_at"), "budgets", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_budgets_user_category_period",
        "budgets",
        ["user_id", "category_id", "period_start"],
        unique=False,
    )
    op.create_index(op.f("ix_budgets_user_id"), "budgets", ["user_id"], unique=False)
    op.create_table(
        "expenses",
        sa.Column(
            "user_id", sa.UUID(), nullable=False, comment="Owner of this expense"
        ),
        sa.Column(
            "category_id",
            sa.UUID(),
            nullable=True,
            comment="Expense category (nullable for uncategorized)",
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Expense amount in user's currency (exact decimal)",
        ),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=False,
            comment="What was this expense for?",
        ),
        sa.Column(
            "date",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the expense occurred (not when it was recorded)",
        ),
        sa.Column(
            "is_recurring",
            sa.Boolean(),
            nullable=False,
            comment="True = this expense recurs automatically",
        ),
        sa.Column(
            "recurring_frequency",
            sa.Enum(
                "DAILY",
                "WEEKLY",
                "BIWEEKLY",
                "MONTHLY",
                "QUARTERLY",
                "YEARLY",
                name="recurring_frequency",
            ),
            nullable=True,
            comment="How often this expense recurs (if is_recurring=True)",
        ),
        sa.Column(
            "recurring_end_date",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When to stop recurring (None = recur forever)",
        ),
        sa.Column(
            "parent_recurring_id",
            sa.UUID(),
            nullable=True,
            comment="For generated recurring expenses: points to the template",
        ),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String(length=50)),
            nullable=True,
            comment="Tags for categorization (e.g., ['business', 'reimbursable'])",
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
            comment="Additional notes about this expense",
        ),
        sa.Column(
            "receipt_url",
            sa.String(length=500),
            nullable=True,
            comment="URL to receipt image (S3 URL in production)",
        ),
        sa.Column(
            "location",
            sa.String(length=200),
            nullable=True,
            comment="Location where expense occurred",
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier (UUID v4)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was last updated",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Soft delete timestamp. NULL means active.",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["parent_recurring_id"], ["expenses.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expenses_category_id"), "expenses", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_expenses_deleted_at"), "expenses", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_expenses_user_category",
        "expenses",
        ["user_id", "category_id"],
        unique=False,
    )
    op.create_index(
        "ix_expenses_user_date", "expenses", ["user_id", "date"], unique=False
    )
    op.create_index(op.f("ix_expenses_user_id"), "expenses", ["user_id"], unique=False)
    op.create_table(
        "income",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "source",
            sa.String(length=200),
            nullable=False,
            comment="Income source (e.g., 'Employer Name', 'Freelance Client')",
        ),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.Column(
            "recurring_frequency",
            sa.Enum(
                "DAILY",
                "WEEKLY",
                "BIWEEKLY",
                "MONTHLY",
                "QUARTERLY",
                "YEARLY",
                name="recurring_frequency",
            ),
            nullable=True,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Unique identifier (UUID v4)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="When this record was last updated",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Soft delete timestamp. NULL means active.",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_income_category_id"), "income", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_income_deleted_at"), "income", ["deleted_at"], unique=False
    )
    op.create_index("ix_income_user_date", "income", ["user_id", "date"], unique=False)
    op.create_index(op.f("ix_income_user_id"), "income", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_income_user_id"), table_name="income")
    op.drop_index("ix_income_user_date", table_name="income")
    op.drop_index(op.f("ix_income_deleted_at"), table_name="income")
    op.drop_index(op.f("ix_income_category_id"), table_name="income")
    op.drop_table("income")
    op.drop_index(op.f("ix_expenses_user_id"), table_name="expenses")
    op.drop_index("ix_expenses_user_date", table_name="expenses")
    op.drop_index("ix_expenses_user_category", table_name="expenses")
    op.drop_index(op.f("ix_expenses_deleted_at"), table_name="expenses")
    op.drop_index(op.f("ix_expenses_category_id"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_budgets_user_id"), table_name="budgets")
    op.drop_index("ix_budgets_user_category_period", table_name="budgets")
    op.drop_index(op.f("ix_budgets_deleted_at"), table_name="budgets")
    op.drop_table("budgets")
    op.drop_index(op.f("ix_user_profiles_deleted_at"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index("ix_categories_user_name", table_name="categories")
    op.drop_index(op.f("ix_categories_user_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_deleted_at"), table_name="categories")
    op.drop_table("categories")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
